In [3]:
import tensorflow as tf
import tensorflow_datasets as tfds
# import keras_hub

In [4]:
raw_train_ds, raw_val_ds = tfds.load('imdb_reviews', split=['train', 'test'])

2026-06-26 08:00:52.380498: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Max
2026-06-26 08:00:52.380530: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 64.00 GB
2026-06-26 08:00:52.380535: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 25.92 GB
I0000 00:00:1782453652.380576 1878823 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1782453652.380624 1878823 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [5]:
for x in raw_train_ds.take(1):
    print(x['text'])
    print(f"label: {x['label']}")

tf.Tensor(b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.", shape=(), dtype=string)
label: 0


2026-06-26 08:00:53.996710: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:387] The default buffer size is 262144, which is overridden by the user specified `buffer_size` of 8388608
2026-06-26 08:00:53.998970: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2026-06-26 08:00:53.999389: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [6]:
for x in raw_train_ds.take(10):
    print(x['label'])

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


2026-06-26 08:00:55.270895: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2026-06-26 08:00:55.271076: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [7]:
train_ds = raw_train_ds.map(lambda x: (x['text'], x['label']))
val_ds = raw_val_ds.take(2048).map(lambda x: (x['text'], x['label']))
val_ds_full = raw_val_ds.map(lambda x: (x['text'], x['label']))
for x, y in train_ds.take(1):
    print(x)
    print(y)

tf.Tensor(b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.", shape=(), dtype=string)
tf.Tensor(0, shape=(), dtype=int64)


2026-06-26 08:00:58.116017: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [8]:
train_ds.save("imdb_reviews/train_ds")
val_ds.save("imdb_reviews/val_ds")

2026-06-26 08:01:47.347244: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [71]:
batch_size = 128
train_ds = train_ds.shuffle(2048).batch(batch_size).prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.shuffle(2048).batch(16).prefetch(
        tf.data.AUTOTUNE
        )
val_ds_full = val_ds_full.batch(16).prefetch(tf.data.AUTOTUNE)

In [6]:
bert_name = "bert_tiny_en_uncased"
tokenizer = keras_hub.models.BertTokenizer.from_preset(bert_name)

In [12]:
text = "This is a test"
text_tk = tokenizer(text)
print(text_tk)

tf.Tensor([2023 2003 1037 3231], shape=(4,), dtype=int32)


In [26]:
for x in raw_train_ds.take(50):
    print(tokenizer(x['text']).shape)

(147,)
(127,)
(176,)
(99,)
(102,)
(350,)
(929,)
(173,)
(289,)
(164,)
(287,)
(343,)
(718,)
(208,)
(467,)
(130,)
(440,)
(670,)
(363,)
(452,)
(275,)
(497,)
(339,)
(134,)
(281,)
(158,)
(228,)
(205,)
(187,)
(194,)
(333,)
(746,)
(298,)
(134,)
(111,)
(289,)
(140,)
(248,)
(129,)
(156,)
(163,)
(642,)
(641,)
(135,)
(177,)
(160,)
(208,)
(622,)
(250,)
(364,)


2026-06-16 10:31:42.510298: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [6]:
preprocessor = keras_hub.models.BertPreprocessor.from_preset(bert_name, sequence_length=512)
backbone = keras_hub.models.BertBackbone.from_preset(bert_name)

In [16]:
preprocessor(text)

{'token_ids': <tf.Tensor: shape=(128,), dtype=int32, numpy=
 array([ 101, 2023, 2003, 1037, 3231,  102,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(128,), dtype=bool, numpy

In [7]:
inp = preprocessor(["hallo", "this is a test"])
y = backbone(inp)
print(y.keys())

dict_keys(['sequence_output', 'pooled_output'])


In [28]:
print(y['pooled_output'].shape)
print(y['sequence_output'].shape)

(2, 128)
(2, 512, 128)


## BertBackbone für Feature Extraktion

In [43]:
preprocessor = keras_hub.models.BertPreprocessor.from_preset(bert_name, sequence_length=512)
backbone = keras_hub.models.BertBackbone.from_preset(bert_name)

inp = preprocessor(["hallo", "this is a test"])
print(inp.keys())
inp['token_ids']

dict_keys(['token_ids', 'padding_mask', 'segment_ids'])


<tf.Tensor: shape=(2, 512), dtype=int32, numpy=
array([[ 101, 2534, 2080, ...,    0,    0,    0],
       [ 101, 2023, 2003, ...,    0,    0,    0]], dtype=int32)>

In [44]:
backbone.trainable = False

input = tf.keras.Input(shape=(), dtype=tf.string)
output = backbone(preprocessor(input))
embedding = output['pooled_output']

x = tf.keras.layers.Dense(128, activation='selu')(embedding)
x = tf.keras.layers.Dense(128, activation='selu')(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dense(16, activation='selu')(x)
y = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(input, y)
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_13      │ (None)            │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_text_classifi… │ [(None, 512),     │          0 │ input_layer_13[0… │
│ (BertTextClassifie… │ (None, 512),      │            │                   │
│                     │ (None, 512)]      │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_backbone       │ [(None, 128),     │  4,385,920 │ bert_text_classi… │
│ (BertBackbone)      │ (None, 512, 128)] │            │ bert_text_classi… │
│                     │                   │            │ bert_text_classi… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_68 (Dense)    │ (None, 128)       │     16,512 │ bert_backbone[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_69 (Dense)    │ (None, 128)       │     16,512 │ dense_68[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_70 (Dense)    │ (None, 64)        │      8,256 │ dense_69[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_71 (Dense)    │ (None, 16)        │      1,040 │ dense_70[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_72 (Dense)    │ (None, 1)         │         17 │ dense_71[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,428,257 (16.89 MB)

 Trainable params: 42,337 (165.38 KB)

 Non-trainable params: 4,385,920 (16.73 MB)

In [45]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [46]:
early_stopping = tf.keras.callbacks.EarlyStopping(
        patience=2,
        monitor='val_loss',
        min_delta=0.01,
        restore_best_weights=True
        )
model.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=[early_stopping], verbose=1)

Epoch 1/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5988 - loss: 0.7020

2026-06-16 12:50:12.248553: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


391/391 ━━━━━━━━━━━━━━━━━━━━ 27s 63ms/step - accuracy: 0.6295 - loss: 0.6532 - val_accuracy: 0.6768 - val_loss: 0.5951
Epoch 2/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 22s 57ms/step - accuracy: 0.6561 - loss: 0.6234 - val_accuracy: 0.6924 - val_loss: 0.5912
Epoch 3/10
  1/391 ━━━━━━━━━━━━━━━━━━━━ 32s 84ms/step - accuracy: 0.5938 - loss: 0.7133

2026-06-16 12:50:35.351950: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


391/391 ━━━━━━━━━━━━━━━━━━━━ 22s 56ms/step - accuracy: 0.6562 - loss: 0.6234 - val_accuracy: 0.6852 - val_loss: 0.5940


2026-06-16 12:50:57.278265: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [13]:
inp_tf = tf.constant(["What an amazing movie!", "A total waste of my time."])
model.predict(inp_tf)

2026-06-16 12:22:09.527826: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 929ms/step


array([[0.41456413],
       [0.6967106 ]], dtype=float32)

## BertClassifier from keras_hub

In [ ]:
# Load a BERT classifier with pre-trained weights.
classifier = keras_hub.models.TextClassifier.from_preset(
        "bert_base_en",
        num_classes=2,
        )
# Fine-tune on IMDb movie reviews (or any dataset).
# imdb_train, imdb_test = tfds.load(
#     "imdb_reviews",
#     split=["train", "test"],
#     as_supervised=True,
#     batch_size=16,
# )
early_stopping = tf.keras.callbacks.EarlyStopping(
        patience=2,
        monitor='val_loss',
        min_delta=0.01,
        )
classifier.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=[early_stopping], verbose=1)
# Predict two new examples.
classifier.predict(["What an amazing movie!", "A total waste of my time."])


## BertClassifier: Eigene Implementierung

In [14]:
class BertClassifier:
    def __init__(self, name, layers, nr_of_classes, activations="ReLU", output_activation="softmax", dropout=None,
                 sequence_length=512
                 ):
        self.name = name
        self.hidden_units = self._ensure_list(layers, "layers")
        self.activations = self._ensure_list(activations, "activations", expected_len=len(self.hidden_units))
        self.output_activation = output_activation
        self.dropouts = self._ensure_list(dropout, "dropout", expected_len=len(self.hidden_units), allow_none=True)
        self.nr_of_classes = nr_of_classes
        self.sequence_length = sequence_length
        self.model = self._build_model()

    @staticmethod
    def _ensure_list(value, argument_name, expected_len=None, allow_none=False):
        if value is None and allow_none:
            values = [None] * expected_len
        elif isinstance(value, (list, tuple)):
            values = list(value)
        else:
            values = [value]

        if expected_len is not None:
            if len(values) == 1 and expected_len != 1 and argument_name != "layers":
                values = values * expected_len
            elif len(values) != expected_len:
                raise ValueError(
                        f"{argument_name} muss entweder ein einzelner Wert sein oder "
                        f"genau {expected_len} Werte enthalten."
                        )
        return values

    @staticmethod
    def _normalize_activation(activation):
        if isinstance(activation, str):
            return activation.lower()
        return activation

    def _build_model(self):
        preprocessor = keras_hub.models.BertPreprocessor.from_preset(
                self.name,
                sequence_length=self.sequence_length,
                )
        backbone = keras_hub.models.BertBackbone.from_preset(self.name)
        backbone.trainable = False

        input_layer = tf.keras.Input(shape=(), dtype=tf.string)
        output = backbone(preprocessor(input_layer))
        x = output["pooled_output"]

        for units, activation, dropout in zip(self.hidden_units, self.activations, self.dropouts):
            x = tf.keras.layers.Dense(
                    units,
                    activation=self._normalize_activation(activation),
                    )(x)
            if dropout is not None:
                x = tf.keras.layers.Dropout(dropout)(x)

        y = tf.keras.layers.Dense(self.nr_of_classes, activation=self.output_activation)(x)
        return tf.keras.Model(input_layer, y, name="bert_classifier")

    def __call__(self, *args, **kwargs):
        return self.model(*args, **kwargs)

    def __getattr__(self, item):
        model = self.__dict__.get("model")
        if model is None:
            raise AttributeError(item)
        return getattr(model, item)


In [50]:
custom_bert_classifier = BertClassifier(
        bert_name,
        layers=[128, 128, 64, 16],
        nr_of_classes=2,
        activations=["selu", "selu", "relu", "selu"],
        sequence_length=512,
        )
custom_bert_classifier.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
custom_bert_classifier.summary()


Model: "bert_classifier"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_15      │ (None)            │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_text_classifi… │ [(None, 512),     │          0 │ input_layer_15[0… │
│ (BertTextClassifie… │ (None, 512),      │            │                   │
│                     │ (None, 512)]      │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_backbone       │ [(None, 128),     │  4,385,920 │ bert_text_classi… │
│ (BertBackbone)      │ (None, 512, 128)] │            │ bert_text_classi… │
│                     │                   │            │ bert_text_classi… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_78 (Dense)    │ (None, 128)       │     16,512 │ bert_backbone[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_79 (Dense)    │ (None, 128)       │     16,512 │ dense_78[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_80 (Dense)    │ (None, 64)        │      8,256 │ dense_79[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_81 (Dense)    │ (None, 16)        │      1,040 │ dense_80[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_82 (Dense)    │ (None, 2)         │         34 │ dense_81[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,428,274 (16.89 MB)

 Trainable params: 42,354 (165.45 KB)

 Non-trainable params: 4,385,920 (16.73 MB)

In [51]:
early_stopping = tf.keras.callbacks.EarlyStopping(
        patience=2,
        monitor='val_loss',
        min_delta=0.01,
        restore_best_weights=True
        )
custom_bert_classifier.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=[early_stopping], verbose=1)

Epoch 1/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6007 - loss: 0.6770

2026-06-16 12:57:13.522479: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


391/391 ━━━━━━━━━━━━━━━━━━━━ 26s 59ms/step - accuracy: 0.6300 - loss: 0.6456 - val_accuracy: 0.7016 - val_loss: 0.5837
Epoch 2/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 22s 57ms/step - accuracy: 0.6644 - loss: 0.6112 - val_accuracy: 0.6336 - val_loss: 0.6347
Epoch 3/10
  2/391 ━━━━━━━━━━━━━━━━━━━━ 22s 57ms/step - accuracy: 0.5469 - loss: 0.6956

2026-06-16 12:57:36.335593: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


391/391 ━━━━━━━━━━━━━━━━━━━━ 21s 54ms/step - accuracy: 0.6671 - loss: 0.6086 - val_accuracy: 0.6984 - val_loss: 0.5811


2026-06-16 12:57:57.448753: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [58]:
custom_bert_classifier.evaluate(val_ds_full)

1563/1563 ━━━━━━━━━━━━━━━━━━━━ 24s 15ms/step - accuracy: 0.6898 - loss: 0.5903


[0.5903002619743347, 0.6898000240325928]

In [59]:
inp_tf = tf.constant(["What an amazing movie!", "A total waste of my time."])
custom_bert_classifier.predict(inp_tf)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[0.42302254, 0.5769775 ],
       [0.66156244, 0.33843753]], dtype=float32)

In [60]:
custom_bert_classifier_256 = BertClassifier(
        bert_name,
        layers=[128, 128, 64, 16],
        nr_of_classes=2,
        activations=["selu", "selu", "relu", "selu"],
        sequence_length=256,
        )
custom_bert_classifier_256.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
custom_bert_classifier_256.summary()

early_stopping = tf.keras.callbacks.EarlyStopping(
        patience=2,
        monitor='val_loss',
        min_delta=0.01,
        restore_best_weights=True
        )
custom_bert_classifier_256.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=[early_stopping], verbose=1)
custom_bert_classifier_256.evaluate(val_ds_full)

Model: "bert_classifier"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_16      │ (None)            │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_text_classifi… │ [(None, 256),     │          0 │ input_layer_16[0… │
│ (BertTextClassifie… │ (None, 256),      │            │                   │
│                     │ (None, 256)]      │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_backbone       │ [(None, 128),     │  4,385,920 │ bert_text_classi… │
│ (BertBackbone)      │ (None, 256, 128)] │            │ bert_text_classi… │
│                     │                   │            │ bert_text_classi… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_83 (Dense)    │ (None, 128)       │     16,512 │ bert_backbone[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_84 (Dense)    │ (None, 128)       │     16,512 │ dense_83[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_85 (Dense)    │ (None, 64)        │      8,256 │ dense_84[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_86 (Dense)    │ (None, 16)        │      1,040 │ dense_85[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_87 (Dense)    │ (None, 2)         │         34 │ dense_86[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,428,274 (16.89 MB)

 Trainable params: 42,354 (165.45 KB)

 Non-trainable params: 4,385,920 (16.73 MB)

Epoch 1/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.6197 - loss: 0.6636 - val_accuracy: 0.6318 - val_loss: 0.6320
Epoch 2/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - accuracy: 0.6484 - loss: 0.6281 - val_accuracy: 0.6206 - val_loss: 0.6437
Epoch 3/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 13s 33ms/step - accuracy: 0.6564 - loss: 0.6212 - val_accuracy: 0.6870 - val_loss: 0.6056
Epoch 4/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 13s 33ms/step - accuracy: 0.6469 - loss: 0.6318 - val_accuracy: 0.6772 - val_loss: 0.6082
Epoch 5/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 13s 33ms/step - accuracy: 0.6623 - loss: 0.6197 - val_accuracy: 0.6045 - val_loss: 0.6613
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 22s 14ms/step - accuracy: 0.6914 - loss: 0.5990


[0.5989614725112915, 0.6914399862289429]

In [63]:
inp_tf = tf.constant(["What an amazing movie!", "A total waste of my time."])
custom_bert_classifier_256.predict(inp_tf)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[0.33441353, 0.6655864 ],
       [0.6017089 , 0.39829105]], dtype=float32)

### BertClassifier: Mehr Schichten

In [64]:
cbc2 = BertClassifier(
        bert_name,
        layers=[256, 256, 128, 64, 32, 16],
        nr_of_classes=2,
        activations="relu",
        sequence_length=512,
        )
cbc2.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
cbc2.summary()


Model: "bert_classifier"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_18      │ (None)            │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_text_classifi… │ [(None, 512),     │          0 │ input_layer_18[0… │
│ (BertTextClassifie… │ (None, 512),      │            │                   │
│                     │ (None, 512)]      │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_backbone       │ [(None, 128),     │  4,385,920 │ bert_text_classi… │
│ (BertBackbone)      │ (None, 512, 128)] │            │ bert_text_classi… │
│                     │                   │            │ bert_text_classi… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_95 (Dense)    │ (None, 256)       │     33,024 │ bert_backbone[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_96 (Dense)    │ (None, 256)       │     65,792 │ dense_95[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_97 (Dense)    │ (None, 128)       │     32,896 │ dense_96[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_98 (Dense)    │ (None, 64)        │      8,256 │ dense_97[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_99 (Dense)    │ (None, 32)        │      2,080 │ dense_98[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_100 (Dense)   │ (None, 16)        │        528 │ dense_99[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_101 (Dense)   │ (None, 2)         │         34 │ dense_100[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,528,530 (17.27 MB)

 Trainable params: 142,610 (557.07 KB)

 Non-trainable params: 4,385,920 (16.73 MB)

In [65]:
early_stopping = tf.keras.callbacks.EarlyStopping(
        patience=3,
        monitor='val_loss',
        min_delta=0.01,
        restore_best_weights=True
        )
cbc2.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=[early_stopping], verbose=1)
cbc2.evaluate(val_ds_full)

Epoch 1/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 25s 58ms/step - accuracy: 0.5565 - loss: 1.1291 - val_accuracy: 0.6152 - val_loss: 0.6400
Epoch 2/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 20s 51ms/step - accuracy: 0.6178 - loss: 0.6975 - val_accuracy: 0.6748 - val_loss: 0.6030
Epoch 3/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 20s 52ms/step - accuracy: 0.6416 - loss: 0.6384 - val_accuracy: 0.6660 - val_loss: 0.6128
Epoch 4/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.6426 - loss: 0.6364 - val_accuracy: 0.6079 - val_loss: 0.6598
Epoch 5/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 21s 54ms/step - accuracy: 0.6246 - loss: 0.6698 - val_accuracy: 0.6851 - val_loss: 0.6006
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 22s 14ms/step - accuracy: 0.6741 - loss: 0.6059


[0.6058587431907654, 0.6740800142288208]

## BertClassifier: Größeres BERT-Modell

In [72]:
bert_small_classifier = BertClassifier(
        "bert_small_en_uncased",
        layers=[128, 64, 32, 16],
        nr_of_classes=2,
        activations="relu",
        sequence_length=512,
        )
bert_small_classifier.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
bert_small_classifier.summary()

Model: "bert_classifier"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_21      │ (None)            │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_text_classifi… │ [(None, 512),     │          0 │ input_layer_21[0… │
│ (BertTextClassifie… │ (None, 512),      │            │                   │
│                     │ (None, 512)]      │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bert_backbone       │ [(None, 512),     │ 28,763,648 │ bert_text_classi… │
│ (BertBackbone)      │ (None, 512, 512)] │            │ bert_text_classi… │
│                     │                   │            │ bert_text_classi… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_112 (Dense)   │ (None, 128)       │     65,664 │ bert_backbone[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_113 (Dense)   │ (None, 64)        │      8,256 │ dense_112[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_114 (Dense)   │ (None, 32)        │      2,080 │ dense_113[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_115 (Dense)   │ (None, 16)        │        528 │ dense_114[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_116 (Dense)   │ (None, 2)         │         34 │ dense_115[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 28,840,210 (110.02 MB)

 Trainable params: 76,562 (299.07 KB)

 Non-trainable params: 28,763,648 (109.72 MB)

### Achtung: Größeres Modell, längere Trainingszeit!

In [73]:
early_stopping = tf.keras.callbacks.EarlyStopping(
        patience=2,
        monitor='val_loss',
        min_delta=0.01,
        restore_best_weights=True
        )
bert_small_classifier.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=[early_stopping], verbose=1)
bert_small_classifier.evaluate(val_ds_full)

Epoch 1/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 150s 748ms/step - accuracy: 0.5734 - loss: 0.7862 - val_accuracy: 0.7773 - val_loss: 0.4927
Epoch 2/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 152s 768ms/step - accuracy: 0.7607 - loss: 0.4946 - val_accuracy: 0.7705 - val_loss: 0.4909
Epoch 3/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 154s 784ms/step - accuracy: 0.7672 - loss: 0.4839 - val_accuracy: 0.7803 - val_loss: 0.4775
Epoch 4/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 150s 763ms/step - accuracy: 0.7719 - loss: 0.4769 - val_accuracy: 0.7993 - val_loss: 0.4513
Epoch 5/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 149s 759ms/step - accuracy: 0.7734 - loss: 0.4754 - val_accuracy: 0.7920 - val_loss: 0.4517
Epoch 6/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 147s 752ms/step - accuracy: 0.7692 - loss: 0.4839 - val_accuracy: 0.7944 - val_loss: 0.4490
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 121s 77ms/step - accuracy: 0.7866 - loss: 0.4532


[0.45318812131881714, 0.7865599989891052]