In [38]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import tensorflow as tf
import tensorflow.keras as keras
import matplotlib.pyplot as plt

plt.rc('font', size=14)
plt.rc('axes', labelsize=14, titlesize=14)
plt.rc('legend', fontsize=14)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
        iris.data, iris.target, test_size=0.1, random_state=42
        )

In [12]:
x = X_train[0]
print(x)

[6.3 3.3 4.7 1.6]


In [14]:
xt = tf.constant(x)
print(xt)

tf.Tensor([6.3 3.3 4.7 1.6], shape=(4,), dtype=float64)


In [3]:
l = keras.layers.Dense(3, activation="softmax")

In [20]:
print(xt.shape)
x_inp = tf.reshape(xt, (1, 4))
print(x_inp.shape)
print(x_inp)

(4,)
(1, 4)
tf.Tensor([[6.3 3.3 4.7 1.6]], shape=(1, 4), dtype=float64)


In [25]:
y_pred = l(x_inp)
print(y_pred.shape)
y_pred

(1, 3)


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.6262301e-03, 3.2398614e-07, 9.9837339e-01]], dtype=float32)>

In [3]:
Xt = tf.constant(X_train[:10])
print(Xt.shape)
l(Xt)

(10, 4)


NameError: name 'l' is not defined

In [11]:
model = keras.Sequential(
        [
                keras.layers.Dense(
                        8,
                        activation="relu",
                        input_shape=(4,),
                        name="hidden_layer",
                        kernel_initializer="he_normal"
                        ),
                keras.layers.Dense(8, activation="relu", name="hidden_layer2"),
                keras.layers.Dense(3, activation="softmax")],
        name="iris_model"
        )
model.summary()

/Users/thomasbayer/Projects/PycharmProjects/lecture/dl_summer/.venv312/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "iris_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hidden_layer (Dense)            │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_layer2 (Dense)           │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 139 (556.00 B)

 Trainable params: 139 (556.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.predict(Xt)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 290ms/step


array([[4.6175402e-02, 9.5382082e-01, 3.7424800e-06],
       [2.1331558e-02, 9.7866768e-01, 7.8068371e-07],
       [8.0598772e-02, 9.1935784e-01, 4.3399021e-05],
       [5.4901980e-02, 9.4508517e-01, 1.2912871e-05],
       [2.3966188e-02, 9.7603261e-01, 1.2524318e-06],
       [2.9334399e-01, 7.0595336e-01, 7.0263754e-04],
       [3.9109867e-02, 9.6088660e-01, 3.6110555e-06],
       [2.8450015e-01, 7.1507013e-01, 4.2964143e-04],
       [2.4578687e-02, 9.7541988e-01, 1.3818035e-06],
       [1.6444208e-02, 9.8355573e-01, 1.3247970e-07]], dtype=float32)

In [16]:
model.fit(X_train, y_train, epochs=50, batch_size=15)


Epoch 1/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.6889 - loss: 0.5471
Epoch 2/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7037 - loss: 0.5430
Epoch 3/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6889 - loss: 0.5380
Epoch 4/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6741 - loss: 0.5335
Epoch 5/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6741 - loss: 0.5273
Epoch 6/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6815 - loss: 0.5248
Epoch 7/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6741 - loss: 0.5183
Epoch 8/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6741 - loss: 0.5147
Epoch 9/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6741 - loss: 0.5098
Epoch 10/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6963 - loss: 0.5045
Epoch 11/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6741 - loss: 0.5017
Epoch 12/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6963 - loss: 0.4960
Epoch 13/5

In [19]:
y_pred = model.predict(X_test)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


(15, 3)

In [23]:
y_pred_classes = tf.argmax(y_pred, axis=1)
print(y_pred_classes.numpy())
print(y_test)

[1 0 2 1 1 0 1 2 2 1 2 0 0 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0]


In [24]:
model.evaluate(X_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.9333 - loss: 0.3463


[0.34631529450416565, 0.9333333373069763]

In [27]:
model.save("iris_model.keras")

In [30]:
model.layers[1].bias

<Variable path=iris_model/hidden_layer2/bias, shape=(8,), dtype=float32, value=[-0.1574198   0.02952101  0.02065234  0.2145164   0.         -0.05051562
  0.          0.        ]>

In [33]:
callback = keras.callbacks.EarlyStopping(monitor='loss', patience=4, min_delta=0.0005)
model.fit(X_train, y_train, epochs=50, batch_size=15, callbacks=[callback])

Epoch 1/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8741 - loss: 0.3287
Epoch 2/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9556 - loss: 0.3181
Epoch 3/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9630 - loss: 0.3189
Epoch 4/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9630 - loss: 0.3163
Epoch 5/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9630 - loss: 0.3125
Epoch 6/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9630 - loss: 0.3101
Epoch 7/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9704 - loss: 0.3075
Epoch 8/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9704 - loss: 0.3051
Epoch 9/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9704 - loss: 0.3011
Epoch 10/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9630 - loss: 0.2994
Epoch 11/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9556 - loss: 0.2981
Epoch 12/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9704 - loss: 0.2936
Epoch 13/5

In [42]:
inp = [5.1, 3.5, 1.4, 0.2]


def classify(inp):
    x_inp = tf.reshape(tf.constant(inp), (1, 4))
    y_pred = model.predict(x_inp)[0]
    print(y_pred.shape)
    y_class = tf.argmax(y_pred).numpy()
    print(f"Predicted probabilities: {y_pred}")
    print(f"Predicted class: {y_class} ({iris.target_names[y_class]})")
    return y_class


classify(inp)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
(3,)
Predicted probabilities: [9.8815572e-01 1.1841786e-02 2.4900053e-06]
Predicted class: 0 (setosa)


np.int64(0)